### ISSUE TITLE
fix: search engine in student grade form not working

### ISSUE THREAD

**Issue by vihao1802** [vihao1802/QuanLyLopHoc_BT1#17]
# When click to search bar, it does not remove the text "Search by ID..." .
![image](https://github.com/Nameless-h/QuanLyLopHoc_BT1/assets/108573121/4acac47e-2356-4c69-9537-fed3c0b8979e)

# When enter a string appears in data table, it does not filter the data.
![image](https://github.com/Nameless-h/QuanLyLopHoc_BT1/assets/108573121/1f3ceab0-bdd2-40c1-846a-1c9f60d8cdc6)

**Comment by Nameless-h** [comment]
Add more feature search by name

**Comment by Nameless-h** [comment]
@BenGuinSan - Add more feature: search by name in student grade form.

**Comment by vihao1802** [comment]
#19 bug: search by name
